model:
  - MolecularGraphMLP
device:
  - cuda:0
batch_size:
  - 64
hidden_units:
  - 300
learning_rate:
  - 0.001
  - 0.01
l2:
  - 0.0
classifier_epochs:
  - 200
optimizer:
  - Adam
activation: 
  - relu
  # - SGD
scheduler:
  - null
loss:
  # - MulticlassClassificationLoss
  - BinaryClassificationLoss

gradient_clipping:
  - null
early_stopper:
#   -
#     class: Patience
#     args:
#       patience: 500
#       use_loss: False
  -
    class: Patience
    args:
      patience: 50
      use_loss: True

shuffle:
  - True

#   'stats_degree': graph_stats_degree,
# 'avg_degree': graph_avg_degree,
# 'avg_cc': node_cc_avg_feature,
# 'cycle': graph_cycle_feature

# 'stats_degree': graph_stats_degree,
# 'degree_dist': graph_degree_dist,
# 'avg_degree': graph_avg_degree,
# 'avg_cc': node_cc_avg_feature,
# 'cycle': graph_cycle_feature,
# 'avgd': graph_avgDN_feature,
# 'invariant':graph_invariant

additional_graph_features:
  - avg_degree
  
dropout:
  - 0.5

norm_feature:
  - True

roc_auc:
  - True

node_attribute:
  - False
  
# sampler:
#   - imbalanced
  
mol_split:
  - True

