model:
  - MolecularFingerprint
device:
  - cuda:0
batch_size:
  - 128
hidden_units:
  - 300
learning_rate:
  - 0.0001
  - 0.001
l2:
  - 0.0
classifier_epochs:
  - 200
optimizer:
  - Adam
  # - SGD
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
  # - BinaryClassificationLoss
gradient_clipping:
  - null
early_stopper:
#   -
#     class: Patience
#     args:
#       patience: 500
#       use_loss: False
  -
    class: Patience
    args:
      patience: 30
      use_loss: True
shuffle:
  - True
  
dropout:
  - 0.5

norm_feature:
  - True

roc_auc:
  - False

node_attribute:
  - False

# sampler:
#   - imbalanced

mol_split:
  - False

edge_attr:
  - True

use_10_fold:
  - True